# Site settings
title: ESS Breeze Base Styles
email: nathan.peters@slalom.com
description: >
  Framework to start building Breeze styling from.
baseurl: "/ess"
url: "http://somethinglikenothing.net"
twitter_username: dv8withn8
github_username: dv8withn8

# Build settings
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :nested
